/** IPC 通道唯一注册表，Preload 和 Main 必须引用这里而不是手写字符串。 */
export const IPC = {
  healthCheck: 'app:health-check',
  todayGet: 'today:get',
  todayAdd: 'today:add',
  todayToggle: 'today:toggle',
  todayEdit: 'today:edit',
  todayDelete: 'today:delete',
  historyGetDay: 'history:get-day',
  historyAdd: 'history:add',
  historyEdit: 'history:edit',
  historyDelete: 'history:delete',
  weekGet: 'week:get',
  reportExport: 'report:export',
  reportOpenLast: 'report:open-last',
  reportRevealLast: 'report:reveal-last',
  windowOpenWeekly: 'window:open-weekly',
  windowShowNote: 'window:show-note',
  appOpenDataFolder: 'app:open-data-folder',
  appSetAlwaysOnTop: 'app:set-always-on-top',
  appQuit: 'app:quit',
  dataChanged: 'event:data-changed',
} as const;
